### GET Test to see if server is up
GET http://localhost:5000

### GET Apes 
GET http://localhost:5000/api/v1/apes

### GET APE
GET http://localhost:5000/api/v1/apes/NKLA

### Create Apes 
POST http://localhost:5000/api/v1/apes/3
### GET Financialprep Sentiment 
GET http://localhost:5000/api/v1/fpsentiment/F

### GET RSI
GET http://localhost:5000/api/v1/income

### POST Portfolio 
POST http://localhost:5000/api/v1/portfolio
Content-Type: application/json

{
    "ticker":"CTRX"
}

### GET 
GET http://localhost:5000/api/v1/portfolio
